url: closetgeekshow.github.io
baseurl: /closetgeekshow
name: Closet Geek Show Podcast
description: An archive of a personal podcast about the strange things people obsess about
remote_theme: riggraz/no-style-please